travis:
  secure:
    BINSTAR_TOKEN: oC/Te6FbvRG8Q8edMOc4qU1qoAJGotmd1V4SdDxXciIWtMoNmy6XNcxj7GfIxLNo1OY5XR5QOTQ5vPucmvXfNK+12rTJ9447OovVNGAbwUXPYHu8YPOcHt4nUAjRFPKUGaFFhb9EPbA9gOglCqMkqRbwRXE3SXMfZRX6NhfCXldEnWDxzUk2P3fM8RHZF3b18q8Juwk0v5TIUh8+OyDn19q9uBF3PiH+b98tkZF//rvkjMQkhIRM/iXLK/eUSEajlVy+VL0ePtpJSfad+7CL54wW5+ae6foLWcZYwsGTuY3UsarUaeqn3sN6Zja/j6gJeRmJbz8ZnL4kZRRXQaV7uFIpJEgSVsrv2880uu2Ty8GmlAtRfObARlxx9ZpbXWFNG/Za9WaUFZMZ8AasOZO5qKRqhOTNbR5VEiMY+SwvoODYw3b0Cw8bPZnzz7FbSQ4fPyJdlr6cQLetOkmEeGbuJi5kf0CF0AxifbLcREo0ZIHK9y+IbKyWtv3748qn0Fb7PItWsnXGnIeo008xeozM0mBt7oTLZ2nxEuljf0f4A1hbuJftxoGaLsB1UPc8Me5yoo/9Fcxv8G7mvtg3PAzTOZXqmKD4ZLUp+MXm31dLTyLfFkH9sL6gwoYcRZuUzaltn2KSYLo0WPtZaPlFbNA/7RJLJU0owyeyWJIZeZrEj90=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
